name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cctools_osx-arm64=1010.6
  - clang=20.1.2
  - clang-20=20.1.2
  - clang_impl_osx-arm64=20.1.2
  - clang_osx-arm64=20.1.2
  - clangxx=20.1.2
  - clangxx_impl_osx-arm64=20.1.2
  - clangxx_osx-arm64=20.1.2
  - comm=0.2.3
  - compiler-rt=20.1.2
  - compiler-rt_osx-arm64=20.1.2
  - debugpy=1.8.18
  - decorator=5.2.1
  - executing=2.2.1
  - gfortran_impl_osx-arm64=14.2.0
  - gfortran_osx-arm64=14.2.0
  - gmp=6.3.0
  - icu=75.1
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - ld64_osx-arm64=951.9
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.2
  - libcxx=20.1.2
  - libcxx-devel=20.1.2
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran-devel_osx-arm64=14.2.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm20=20.1.2
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - llvm-tools=20.1.2
  - llvm-tools-20=20.1.2
  - matplotlib-inline=0.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.0.1
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.12
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.2
  - scipy=1.15.2
  - setuptools=78.1.0
  - sigtool=0.1.3
  - six=1.17.0
  - stack_data=0.6.3
  - tapi=1300.6.5
  - tk=8.6.13
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.3.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.5.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.4.3
      - multiprocess==0.70.18
      - networkx==3.4.2
      - numpy==2.3.5
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==11.2.1
      - propcache==0.3.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - seaborn==0.13.2
      - sentry-sdk==2.47.0
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.6.0
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - wandb==0.23.1
      - xxhash==3.6.0
      - yarl==1.19.0
